# Generated by Django 2.0.1 on 2018-01-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer1_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='author',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
