# Generated by Django 2.0.1 on 2018-01-22 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180122_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='student',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
