# Generated by Django 2.0.1 on 2018-01-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_answer2_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer2',
            old_name='student',
            new_name='student_2',
        ),
    ]
