# Generated by Django 2.0.1 on 2018-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20180123_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer1',
            name='question_answer',
            field=models.CharField(help_text=None, max_length=1),
        ),
    ]
